import type { User } from '@/lib/types';

// Use a global variable in development to preserve data across HMR
declare global {
  var __usersData__: User[] | undefined;
}

const initialData: User[] = [
    {
        id: 'user-001',
        name: 'John Doe',
        email: 'agent@gmail.com',
        role: 'agent',
        walletAddress: 'spark1q...user01',
        kycStatus: 'verified',
        kybStatus: 'verified',
        kytStatus: 'verified',
        status: 'active',
        phone: '+1 555-0101',
        kycLevel: 3,
        kybLevel: 2,
        legalName: 'Johnathan Doe',
        address: '456 Oak Avenue, Financial District',
        businessName: 'Global Agents Co.',
        businessLegalName: 'Global Agents Company LLC',
        businessRegistrationId: 'GA-12345',
        businessAddress: '123 Agent Avenue, Suite 100, Financial District',
        industry: 'Consulting',
    },
    {
        id: 'user-002',
        name: 'Jane Smith',
        email: 'issuer@gmail.com',
        role: 'issuer',
        walletAddress: 'spark1q...user02',
        kycStatus: 'pending',
        kybStatus: 'pending',
        status: 'active',
        phone: '+1 555-0102',
        kycLevel: 1,
        kybLevel: 1,
        legalName: 'Jane Elizabeth Smith',
        dob: '1985-11-05',
        idDoc: 'DUI: 01234567-8',
        address: 'Residencial Las Flores, #123, San Salvador',
        country: 'El Salvador',
        city: 'San Salvador',
        businessName: 'Emisores de Activos Digitales',
        businessLegalName: 'Emisores de Activos Digitales, S.A. de C.V.',
        businessAddress: 'Edificio Avante, Suite 501, San Salvador, El Salvador',
        businessRegistrationId: 'NRC: 12345-6',
        industry: 'FinTech',
    },
    {
        id: 'user-003',
        name: 'Peter Jones',
        email: 'investor@gmail.com',
        role: 'investor',
        walletAddress: 'spark1q...user03',
        kycStatus: 'verified',
        status: 'active',
        phone: '+1 555-0103',
        kycLevel: 2,
        country: 'El Salvador',
        legalName: 'Peter Bartholomew Jones',
        idDoc: 'ID Card, 06**********38',
        address: 'San Salvador Centro, El Salvador',
    },
    {
        id: 'user-004',
        name: 'Mary Poppins',
        email: 'mary.poppins@example.com',
        role: 'agent',
        walletAddress: 'spark1q...user04',
        kycStatus: 'rejected',
        kybStatus: 'pending',
        status: 'active',
        phone: '+1 555-0104',
        kycLevel: 0,
        kybLevel: 0,
        legalName: 'Mary P. Poppins',
        address: '17 Cherry Tree Lane, London',
        businessName: 'Poppins & Co. Associates',
        businessLegalName: 'Poppins & Co. Associates Ltd.',
        businessAddress: '18 Cherry Tree Lane, London',
        businessRegistrationId: 'PC-98765',
        industry: 'Financial Services',
    },
     {
        id: 'user-005',
        name: 'Super Admin',
        email: 'superadmin@gmail.com',
        role: 'superadmin',
        walletAddress: 'spark1q...superadmin',
        kycStatus: 'verified',
        kybStatus: 'verified',
        status: 'active',
        phone: '+1 555-0105',
        kycLevel: 4,
        kybLevel: 4,
        legalName: 'S. Admin',
        address: '2 Infinite Loop, Cupertino, CA',
        businessName: 'BlockStratus Platform',
        businessLegalName: 'BlockStratus Inc.',
        businessAddress: '1 Infinite Loop, Cupertino, CA',
        businessRegistrationId: 'BS-ADMIN-001',
        industry: 'Technology',
    }
];

// To prevent the data from being lost on hot-reloads in development
if (process.env.NODE_ENV !== 'production' && !global.__usersData__) {
  global.__usersData__ = [...initialData];
}

export let usersData: User[] = global.__usersData__ || initialData;
